name: asan
on:
  pull_request:
  schedule:
    - cron: '42 0 * * *'

jobs:
  asan:
    name: Address Santization
    uses: open-rmf/rmf_ci_templates/.github/workflows/reusable_asan.yaml@main
    with:
      packages: rmf_traffic
      dist-matrix: |
        [{"ros_distribution": "lyrical",
          "ubuntu_distribution": "resolute"}]
