name: tsan

on:
  pull_request:
  workflow_dispatch:

jobs:
  tsan_test:
    name: rmf_traffic-tsan
    uses: open-rmf/rmf_ci_templates/.github/workflows/reusable_build.yaml@main
    with:
      dist-matrix: |
          [{"ros_distribution": "humble",
            "ubuntu_distribution": "jammy"}]
      # NOTE: Avoid adding comments in the package lines, this can break some of the called scripts in github actions
      packages: |
        rmf_traffic
        rmf_traffic_examples
      mixin: tsan
