name: tsan
on: [push, pull_request]
jobs:
  tsan:
    name: tsan
    runs-on: ubuntu-20.04
    steps:
      - name: deps
        uses: ros-tooling/setup-ros@v0.1
        with:
          required-ros-distributions: foxy
      - name: build_and_test
        uses: ros-tooling/action-ros-ci@v0.2
        env:
          CC: clang
          CXX: clang++
        with:
          target-ros2-distro: foxy
          # build all packages listed in the meta package
          package-name: |
            rmf_traffic
          vcs-repo-file-url: |
            https://raw.githubusercontent.com/open-rmf/rmf/main/rmf.repos
          colcon-defaults: |
            {
              "build": {
                "mixin": ["tsan"],
                "cmake-args": ["-DCMAKE_BUILD_TYPE=Debug"]
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml

